name: Ruly tests
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install requirements
        run: "pip install -r requirements.txt"
      - name: Plat tests
        run: "doit plat_test"