name: Ruly platform tests
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install requirements
        run: "pip install -r requirements.txt"
      - name: Build wheel
        run: "doit dist"
      - name: Upload wheel
        uses: "actions/upload-artifact@master"
        with:
          name: wheel
          path: ./dist
  test:
    needs: ["build"]
    strategy:
      matrix:
        versions:
          - os: "ubuntu-20-04"
            python: "3.6"
          - os: "ubuntu-latest"
            python: "3.7"
          - os: "ubuntu-latest"
            python: "3.8"
          - os: "ubuntu-latest"
            python: "3.9"
          - os: "ubuntu-latest"
            python: "3.10"
          - os: "ubuntu-latest"
            python: "3.11"
          - os: "ubuntu-latest"
            python: "3.12"
    runs-on: ${{ matrix.versions.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.versions.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.versions.python }}
      - name: Download Ruly wheel
        uses: actions/download-artifact@master
        with:
          name: wheel
          path: ./dist
      - name: Run tests
        run: |
          python -m pip install --upgrade pip
          pip install pytest ./dist/*.whl
          pytest