name: Ruly platform tests
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install requirements
        run: "pip install -r requirements.txt"
      - name: Build wheel
        run: "doit dist"
      - name: Upload wheel
        uses: "actions/upload-artifact@master"
        with:
          name: wheel
          path: ./dist